"""
License Server Configuration — manages which servers the validator contacts.

Security model:
  - Server URLs come from a RSA-PSS signed file (data/license_servers.signed)
  - The file is generated by the vendor at release time using their private key
  - Customers cannot forge or modify it without the private key
  - In dev (no license_public.pem): env vars LICENSE_SERVER_URL / _BACKUP work
  - Migration codes: time-limited, nonce-protected, RSA-PSS signed by vendor
"""

import base64
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Tuple

logger = logging.getLogger(__name__)

# ── Compiled-in fallback URLs (set by build_release.sh via sed) ───────────────
# If license_servers.signed is missing or tampered, these are used.
# VENDOR: set your real URLs in build_release.sh — do not edit this placeholder.
_FALLBACK_PRIMARY = ""   # VENDOR_PRIMARY_PLACEHOLDER
_FALLBACK_BACKUP  = ""   # VENDOR_BACKUP_PLACEHOLDER

# ── Paths ─────────────────────────────────────────────────────────────────────
_BASE_DIR     = Path(__file__).parent.parent.parent.parent
_SERVERS_FILE = _BASE_DIR / "data" / "license_servers.signed"
_NONCES_FILE  = _BASE_DIR / "data" / "license_migration_nonces.json"
_PUB_KEY_PATH = _BASE_DIR / "server_verify_public.pem"


def _is_production() -> bool:
    """True when license_public.pem exists (production deployment)."""
    candidates = [
        _BASE_DIR / "license_public.pem",
        Path("/opt/vpnmanager/license_public.pem"),
    ]
    return any(p.exists() for p in candidates)


def _load_pub_key():
    path = Path(os.getenv("SERVER_VERIFY_PUBLIC_KEY_PATH", str(_PUB_KEY_PATH)))
    if not path.exists():
        return None
    try:
        from cryptography.hazmat.primitives.serialization import load_pem_public_key
        return load_pem_public_key(path.read_bytes())
    except Exception as exc:
        logger.error("Failed to load server_verify_public.pem: %s", exc)
        return None


def _verify_signed(data: dict):
    """Verify RSA-PSS signature and return decoded payload dict, or None."""
    pub_key = _load_pub_key()
    if pub_key is None:
        return None
    try:
        payload_b64 = data.get("payload", "")
        sig_b64     = data.get("signature", "")

        from cryptography.hazmat.primitives import hashes
        from cryptography.hazmat.primitives.asymmetric import padding

        pad = (4 - len(payload_b64) % 4) % 4
        payload_bytes = base64.urlsafe_b64decode(payload_b64 + "=" * pad)
        pad2 = (4 - len(sig_b64) % 4) % 4
        sig_bytes = base64.urlsafe_b64decode(sig_b64 + "=" * pad2)

        pub_key.verify(
            sig_bytes,
            payload_b64.encode("ascii"),
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH,
            ),
            hashes.SHA256(),
        )
        return json.loads(payload_bytes)
    except Exception as exc:
        logger.error("Signed data verification failed: %s", exc)
        return None


def get_server_urls() -> Tuple[str, str]:
    """
    Return (primary_url, backup_url).

    Source priority:
      1. data/license_servers.signed — RSA-verified, production source (cannot be forged)
      2. Env vars  — fallback for dev/testing when signed file is absent
      3. Compiled-in fallback constants (set by build_release.sh)

    Security: if the signed file exists and is valid, env vars are never reached.
    This means customers cannot override server URLs in production.
    """
    # Try signed config file first — takes precedence over everything
    try:
        if _SERVERS_FILE.exists():
            data    = json.loads(_SERVERS_FILE.read_text())
            payload = _verify_signed(data)
            if payload:
                return (
                    payload.get("primary", "").rstrip("/"),
                    payload.get("backup",  "").rstrip("/"),
                )
            else:
                logger.warning(
                    "license_servers.signed failed signature check — "
                    "falling back to env vars / compiled-in URLs"
                )
    except Exception as exc:
        logger.error("Failed to read license_servers.signed: %s", exc)

    # Env vars — work in dev/test when signed file is absent or failed
    primary = os.getenv("LICENSE_SERVER_URL", "").rstrip("/")
    backup  = os.getenv("LICENSE_SERVER_URL_BACKUP", "").rstrip("/")
    if primary or backup:
        return primary, backup

    return _FALLBACK_PRIMARY, _FALLBACK_BACKUP


def get_server_info() -> dict:
    """Return current server config info for the admin panel."""
    primary, backup = get_server_urls()
    if _SERVERS_FILE.exists():
        source = "signed_file"
    elif os.getenv("LICENSE_SERVER_URL"):
        source = "env_var_dev"
    else:
        source = "fallback"
    return {
        "primary_url": primary or None,
        "backup_url":  backup  or None,
        "source":      source,
    }


def apply_migration_code(code_json: str) -> Tuple[bool, str]:
    """
    Apply a server migration code issued by the vendor.

    Migration code format (JSON string):
      {
        "payload":   "base64url({primary, backup, issued_at, expires_at, nonce})",
        "signature": "base64url(rsa-pss-sig-with-server_verify_private.pem)"
      }

    Security:
      - RSA-PSS signature verified with server_verify_public.pem
      - expires_at enforced (vendor sets e.g. 30-day window)
      - nonce tracked to prevent replay attacks
    """
    try:
        data = json.loads(code_json.strip())
    except Exception:
        return False, "Invalid JSON format"

    payload = _verify_signed(data)
    if payload is None:
        return False, "Invalid signature — code rejected"

    # Check expiry
    expires_str = payload.get("expires_at", "")
    if not expires_str:
        return False, "Migration code is missing expiry date"
    try:
        expires_at = datetime.fromisoformat(expires_str)
        if expires_at.tzinfo is None:
            expires_at = expires_at.replace(tzinfo=timezone.utc)
        if datetime.now(timezone.utc) > expires_at:
            return False, "Migration code has expired"
    except Exception:
        return False, "Invalid expiry date format"

    # Nonce anti-replay
    nonce = payload.get("nonce", "")
    if not nonce:
        return False, "Migration code is missing nonce"
    used_nonces = _load_nonces()
    if nonce in used_nonces:
        return False, "Migration code already used (replay attack detected)"

    # Validate new URLs
    new_primary = payload.get("primary", "").rstrip("/")
    new_backup  = payload.get("backup",  "").rstrip("/")
    if not new_primary:
        return False, "Migration code is missing primary server URL"
    if not new_primary.startswith(("http://", "https://")):
        return False, "Primary server URL must start with http:// or https://"
    if new_backup and not new_backup.startswith(("http://", "https://")):
        return False, "Backup server URL must start with http:// or https://"

    # Save new signed config (re-use the signed bundle as-is — signature already verified)
    try:
        _SERVERS_FILE.parent.mkdir(parents=True, exist_ok=True)
        _SERVERS_FILE.write_text(json.dumps(data, indent=2))
    except Exception as exc:
        return False, f"Failed to save new server config: {exc}"

    # Record nonce
    used_nonces.append(nonce)
    _save_nonces(used_nonces)

    logger.info(
        "License server migration applied: primary=%s backup=%s",
        new_primary, new_backup or "—"
    )
    return True, f"Migration applied. New server: {new_primary}"


def _load_nonces() -> list:
    try:
        if _NONCES_FILE.exists():
            return json.loads(_NONCES_FILE.read_text())
    except Exception:
        pass
    return []


def _save_nonces(nonces: list):
    try:
        _NONCES_FILE.parent.mkdir(parents=True, exist_ok=True)
        _NONCES_FILE.write_text(json.dumps(nonces[-500:]))  # keep last 500 max
    except Exception as exc:
        logger.error("Failed to save used nonces: %s", exc)
