"""
VPN Management Studio API - Server Routes
WireGuard server management
"""

from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session
from loguru import logger
import asyncio
import json
import re
from datetime import datetime, timezone

from ...database.connection import get_db
from ...database.models import Server, Client, ServerStatus, ServerLifecycleStatus, ClientStatus
from ...core.management import ManagementCore
from ...core.wireguard import WireGuardManager
from ..middleware.license_gate import require_license_feature


router = APIRouter()

# Multi-server orchestration gate (remote-server discovery, agent install).
# Server creation has its own inline check (it also needs to count existing
# servers against the per-tier max), so we don't gate the create endpoint here.
_multi_server_gate = Depends(require_license_feature("multi_server"))


def _safe_filename(name: str) -> str:
    """Sanitize name for Content-Disposition header (ASCII-safe)."""
    return re.sub(r'[^\w\-.]', '_', name) or "server"


# ============================================================================
# SCHEMAS
# ============================================================================

class ServerCreate(BaseModel):
    """Schema for creating a new server"""
    name: str = Field(..., min_length=1, max_length=100)
    endpoint: str = Field(..., description="Public endpoint (ip:port)")
    public_key: Optional[str] = Field(None, min_length=44, max_length=44)
    private_key: Optional[str] = Field(None, min_length=44, max_length=44)
    interface: str = Field("wg0", pattern=r"^(wg|awg)\d+$")
    listen_port: int = Field(51820, ge=1, le=65535)
    address_pool_ipv4: str = Field("10.66.66.0/24")
    address_pool_ipv6: Optional[str] = Field("fd42:42:42::/64")
    dns: str = Field("1.1.1.1,1.0.0.1")
    max_clients: int = Field(250, ge=1)
    description: Optional[str] = None
    location: Optional[str] = None
    ssh_host: Optional[str] = Field(None, description="SSH host for remote management")
    ssh_port: int = Field(22, ge=1, le=65535)
    ssh_user: str = Field("root")
    ssh_password: Optional[str] = Field(None, description="SSH password")
    ssh_private_key: Optional[str] = Field(None, description="SSH private key content (PEM). Use instead of password.")
    # Protocol type: vpn or proxy
    server_type: str = Field(
        "wireguard",
        pattern=r"^(wireguard|amneziawg|hysteria2|tuic)$",
        description="Protocol: wireguard | amneziawg | hysteria2 | tuic",
    )
    # AmneziaWG obfuscation params (VPN only)
    awg_jc: Optional[int] = Field(None, ge=1, le=128)
    awg_jmin: Optional[int] = Field(None, ge=0, le=65535)
    awg_jmax: Optional[int] = Field(None, ge=0, le=65535)
    awg_s1: Optional[int] = Field(None, ge=0, le=65535)
    awg_s2: Optional[int] = Field(None, ge=0, le=65535)
    awg_h1: Optional[int] = Field(None, ge=1)
    awg_h2: Optional[int] = Field(None, ge=1)
    awg_h3: Optional[int] = Field(None, ge=1)
    awg_h4: Optional[int] = Field(None, ge=1)
    awg_mtu: Optional[int] = Field(None, ge=576, le=9000, description="MTU for AWG (default 1280 if not set)")
    supports_peer_visibility: bool = Field(True, description="Whether this server supports peer visibility")
    split_tunnel_support: bool = Field(False, description="Use VPN subnet AllowedIPs to enable AmneziaVPN split tunneling")
    provision: bool = Field(False, description="Provision a fresh server: install protocol, generate keys/certs, start service")
    task_id: Optional[str] = Field(None, description="Bootstrap task ID for progress tracking (generated by frontend)")
    # Proxy protocol fields (hysteria2 / tuic)
    proxy_domain: Optional[str] = Field(None, description="Domain name for TLS SNI (proxy only)")
    proxy_tls_mode: str = Field("self_signed", description="TLS mode: self_signed | acme | manual (proxy only)")
    proxy_cert_path: Optional[str] = Field(None, description="Path to TLS cert on server (proxy manual TLS)")
    proxy_key_path: Optional[str] = Field(None, description="Path to TLS key on server (proxy manual TLS)")
    proxy_obfs_password: Optional[str] = Field(None, description="OBFS password (Hysteria2 only)")

    class Config:
        json_schema_extra = {
            "example": {
                "name": "Amsterdam Server",
                "endpoint": "1.2.3.4:51820",
                "public_key": "example_public_key_base64_44chars==",
                "private_key": "example_private_key_base64_44chars=",
                "interface": "wg1",
                "location": "Netherlands",
                "ssh_host": "1.2.3.4",
                "ssh_password": "secret"
            }
        }


class ServerUpdate(BaseModel):
    """Schema for updating a server"""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    display_name: Optional[str] = Field(None, max_length=100)
    endpoint: Optional[str] = None
    dns: Optional[str] = None
    max_clients: Optional[int] = Field(None, ge=1)
    max_bandwidth_mbps: Optional[int] = Field(None, ge=0)
    description: Optional[str] = None
    location: Optional[str] = None
    supports_peer_visibility: Optional[bool] = None
    split_tunnel_support: Optional[bool] = None


class ProxyInstallRequest(BaseModel):
    """Schema for installing a proxy protocol on an existing SSH-accessible server."""
    protocol: str = Field("hysteria2", pattern=r"^(hysteria2|tuic)$")
    name: Optional[str] = None
    port: Optional[int] = Field(None, ge=1, le=65535)
    tls_mode: str = Field("self_signed", pattern=r"^(self_signed|acme|manual)$")
    domain: Optional[str] = None
    cert_path: Optional[str] = None
    key_path: Optional[str] = None
    obfs_password: Optional[str] = None  # Hysteria2 only
    task_id: Optional[str] = None


class ServerResponse(BaseModel):
    """Server response schema"""
    id: int
    name: str
    display_name: Optional[str] = None
    interface: str
    endpoint: str
    listen_port: int
    status: str
    lifecycle_status: str
    is_active: bool = True
    max_clients: int
    total_clients: int = 0
    description: Optional[str]
    location: Optional[str]
    ssh_host: Optional[str] = None
    ssh_port: int = 22
    ssh_user: str = "root"
    is_remote: bool = False
    agent_mode: str = "ssh"  # "ssh" or "agent"
    agent_url: Optional[str] = None
    max_bandwidth_mbps: Optional[int] = None
    is_default: bool = False
    server_type: str = "wireguard"
    server_category: str = "vpn"
    # VPN (WG/AWG) fields
    awg_jc: Optional[int] = None
    awg_jmin: Optional[int] = None
    awg_jmax: Optional[int] = None
    awg_s1: Optional[int] = None
    awg_s2: Optional[int] = None
    awg_h1: Optional[int] = None
    awg_h2: Optional[int] = None
    awg_h3: Optional[int] = None
    awg_h4: Optional[int] = None
    awg_mtu: Optional[int] = None
    supports_peer_visibility: bool = True
    split_tunnel_support: bool = False
    # Proxy fields
    proxy_domain: Optional[str] = None
    proxy_tls_mode: Optional[str] = None
    proxy_cert_path: Optional[str] = None
    proxy_key_path: Optional[str] = None
    proxy_config_path: Optional[str] = None
    proxy_service_name: Optional[str] = None

    class Config:
        from_attributes = True

    @classmethod
    def from_server(cls, server, db=None):
        total_clients = 0
        if db:
            total_clients = db.query(Client).filter(Client.server_id == server.id).count()

        server_type = getattr(server, 'server_type', 'wireguard') or 'wireguard'
        server_category = getattr(server, 'server_category', None)
        if not server_category:
            server_category = 'proxy' if server_type in ('hysteria2', 'tuic') else 'vpn'

        return cls(
            id=server.id,
            name=server.name,
            display_name=getattr(server, 'display_name', None),
            interface=server.interface,
            endpoint=server.endpoint,
            listen_port=server.listen_port,
            status=server.legacy_status.value if hasattr(server, 'legacy_status') else (server.status.value if hasattr(server.status, 'value') else str(server.status)),
            lifecycle_status=server.effective_lifecycle_status if hasattr(server, 'effective_lifecycle_status') else str(server.status),
            is_active=getattr(server, 'is_active', True),
            max_clients=server.max_clients,
            total_clients=total_clients,
            description=server.description,
            location=server.location,
            ssh_host=server.ssh_host,
            ssh_port=server.ssh_port or 22,
            ssh_user=server.ssh_user or "root",
            is_remote=server.ssh_host is not None,
            agent_mode=server.agent_mode or "ssh",
            agent_url=server.agent_url,
            max_bandwidth_mbps=server.max_bandwidth_mbps,
            is_default=getattr(server, 'is_default', False) or False,
            server_type=server_type,
            server_category=server_category,
            awg_jc=getattr(server, 'awg_jc', None),
            awg_jmin=getattr(server, 'awg_jmin', None),
            awg_jmax=getattr(server, 'awg_jmax', None),
            awg_s1=getattr(server, 'awg_s1', None),
            awg_s2=getattr(server, 'awg_s2', None),
            awg_h1=getattr(server, 'awg_h1', None),
            awg_h2=getattr(server, 'awg_h2', None),
            awg_h3=getattr(server, 'awg_h3', None),
            awg_h4=getattr(server, 'awg_h4', None),
            awg_mtu=getattr(server, 'awg_mtu', None),
            supports_peer_visibility=getattr(server, 'supports_peer_visibility', True),
            split_tunnel_support=getattr(server, 'split_tunnel_support', False),
            proxy_domain=getattr(server, 'proxy_domain', None),
            proxy_tls_mode=getattr(server, 'proxy_tls_mode', None),
            proxy_cert_path=getattr(server, 'proxy_cert_path', None),
            proxy_key_path=getattr(server, 'proxy_key_path', None),
            proxy_config_path=getattr(server, 'proxy_config_path', None),
            proxy_service_name=getattr(server, 'proxy_service_name', None),
        )


class DiscoverRequest(BaseModel):
    """Schema for discovering a remote server"""
    ssh_host: str = Field(..., description="SSH host/IP")
    ssh_port: int = Field(22, ge=1, le=65535)
    ssh_user: str = Field("root")
    ssh_password: Optional[str] = Field(None, description="SSH password")
    ssh_private_key: Optional[str] = Field(None, description="SSH private key content (PEM). Use instead of password.")
    interface: str = Field("wg0", pattern=r"^(wg|awg)\d+$")
    server_name: Optional[str] = Field(None, description="Name for the server (auto-generated if empty)")


class ServerStatsResponse(BaseModel):
    """Server statistics response"""
    server_id: int
    name: str
    interface: str
    status: str
    endpoint: str
    total_clients: int
    active_clients: int
    max_clients: int
    capacity_percent: float
    total_rx: int
    total_tx: int
    total_traffic: int
    is_online: bool


class AgentInstallRequest(BaseModel):
    """Schema for agent installation"""
    port: int = Field(8001, ge=1, le=65535, description="Agent API port")


# ============================================================================
# ENDPOINTS
# ============================================================================

@router.get("")
async def list_servers(
    include_offline: bool = Query(True, description="Include offline servers"),
    limit: int = Query(100, ge=1, le=500, description="Max items to return"),
    offset: int = Query(0, ge=0, description="Number of items to skip"),
    db: Session = Depends(get_db)
):
    """
    Get list of all WireGuard servers with pagination
    """
    query = db.query(Server)

    if not include_offline:
        query = query.filter(Server.lifecycle_status == ServerLifecycleStatus.ONLINE.value)

    total = query.count()
    servers = query.order_by(Server.name).offset(offset).limit(limit).all()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "items": [ServerResponse.from_server(s, db=db) for s in servers]
    }


@router.post("", response_model=ServerResponse, status_code=201)
async def create_server(
    server_data: ServerCreate,
    db: Session = Depends(get_db)
):
    """
    Create a new WireGuard server configuration

    NEW BEHAVIOR:
    - For remote servers (ssh_host provided): automatically installs agent
    - SSH is used ONLY for bootstrap
    - After installation, server switches to agent mode
    - User sees progress: SSH → Installing → Agent Online
    """
    from loguru import logger
    import os

    # License enforcement: check server limit and multi_server feature.
    # Advisory lock (key 1000002) prevents concurrent requests from both passing the check.
    try:
        from sqlalchemy import text as _sql_text
        from ...modules.license.manager import get_license_manager
        db.execute(_sql_text("SELECT pg_advisory_xact_lock(1000002)"))
        mgr = get_license_manager()
        info = mgr.get_license_info()
        current_count = db.query(Server).count()
        if not info.can_add_server(current_count):
            raise HTTPException(
                status_code=403,
                detail=f"License limit reached: {current_count}/{info.max_servers} servers. Upgrade your license."
            )
        if current_count >= 1 and not info.has_feature("multi_server"):
            raise HTTPException(
                status_code=403,
                detail="Multi-server feature requires Business or Enterprise license."
            )
    except HTTPException:
        raise
    except Exception as _lic_err:
        from loguru import logger
        logger.error(f"License check failed during server creation: {_lic_err}")
        raise HTTPException(status_code=503, detail="License verification unavailable")

    # License enforcement: per-protocol feature gating.
    # FREE tier supports WireGuard + AmneziaWG; Hysteria2/TUIC require the
    # `proxy_protocols` feature (Starter+). Trial keeps WireGuard-only.
    if server_data.server_type != "wireguard":
        try:
            _proto_feature_map = {
                "amneziawg":  "amneziawg",
                "hysteria2":  "proxy_protocols",
                "tuic":       "proxy_protocols",
            }
            _required = _proto_feature_map.get(server_data.server_type)
            if _required and not info.has_feature(_required):
                raise HTTPException(
                    status_code=403,
                    detail=(
                        f"{server_data.server_type.upper()} protocol requires the "
                        f"'{_required}' feature. Upgrade your plan to enable it."
                    ),
                )
        except HTTPException:
            raise
        except Exception:
            pass  # If license check unavailable, allow (fail-open)

    core = ManagementCore(db)

    # Check if server with same name exists
    if core.servers.get_server_by_name(server_data.name):
        raise HTTPException(
            status_code=400,
            detail=f"Server '{server_data.name}' already exists"
        )

    # ── Route proxy protocols to their own creation flow ──────────────────────
    is_proxy = server_data.server_type in ("hysteria2", "tuic")
    if is_proxy:
        return await _create_proxy_server(server_data, db, core)

    # Check if interface is already used (only for local servers)
    if not server_data.ssh_host and core.servers.get_server_by_interface(server_data.interface):
        raise HTTPException(
            status_code=400,
            detail=f"Interface '{server_data.interface}' is already in use"
        )

    public_key = server_data.public_key
    private_key = server_data.private_key
    listen_port = server_data.listen_port
    address_pool_ipv4 = server_data.address_pool_ipv4

    is_awg = server_data.server_type == "amneziawg"

    # For AmneziaWG: auto-generate obfuscation params if not provided
    awg_params = {}
    _awg_auto = {}
    if is_awg:
        from ...core.amneziawg import AmneziaWGManager
        _awg_auto = AmneziaWGManager.generate_obfuscation_params()
        # Start with auto-generated values; will be overridden by discovered/user values below
        awg_params = {
            "awg_jc":   _awg_auto["jc"],
            "awg_jmin": _awg_auto["jmin"],
            "awg_jmax": _awg_auto["jmax"],
            "awg_s1":   _awg_auto["s1"],
            "awg_s2":   _awg_auto["s2"],
            "awg_h1":   _awg_auto["h1"],
            "awg_h2":   _awg_auto["h2"],
            "awg_h3":   _awg_auto["h3"],
            "awg_h4":   _awg_auto["h4"],
        }

    # For remote servers without keys: try to discover existing WG/AWG config.
    # If config not found (fresh server) — automatically fall into provision mode.
    if server_data.ssh_host and (not public_key or not private_key):
        logger.info(f"Fetching keys from remote server {server_data.ssh_host}...")
        if is_awg:
            from ...core.amneziawg import AmneziaWGManager
            wg = AmneziaWGManager(
                interface=server_data.interface,
                config_path=f"/etc/amneziawg/{server_data.interface}.conf",
                ssh_host=server_data.ssh_host,
                ssh_port=server_data.ssh_port,
                ssh_user=server_data.ssh_user,
                ssh_password=server_data.ssh_password,
                ssh_private_key=server_data.ssh_private_key,
            )
        else:
            from ...core.wireguard import WireGuardManager
            wg = WireGuardManager(
                interface=server_data.interface,
                config_path=f"/etc/wireguard/{server_data.interface}.conf",
                ssh_host=server_data.ssh_host,
                ssh_port=server_data.ssh_port,
                ssh_user=server_data.ssh_user,
                ssh_password=server_data.ssh_password,
                ssh_private_key=server_data.ssh_private_key,
            )
        try:
            result = await asyncio.to_thread(wg.discover_remote)
            wg.close()
            if result:
                # Existing VPN found — use discovered keys and params
                public_key  = result["public_key"]
                private_key = result["private_key"]
                listen_port = result.get("listen_port", listen_port)
                if result.get("address_pool_ipv4"):
                    address_pool_ipv4 = result["address_pool_ipv4"]
                if is_awg and result.get("awg_params"):
                    for k, v in result["awg_params"].items():
                        if not getattr(server_data, f"awg_{k}", None):
                            awg_params[f"awg_{k}"] = v
                logger.info(f"Discovered existing VPN on {server_data.ssh_host}: pub={public_key[:12]}...")
            else:
                # No existing config — provision fresh server automatically
                logger.info(f"No VPN config found on {server_data.ssh_host} — switching to provision mode")
                server_data.provision = True
        except Exception as e:
            wg.close()
            raise HTTPException(
                status_code=400,
                detail=f"SSH connection failed to {server_data.ssh_host}: {str(e)}"
            )

    # Apply user-provided AWG params last (highest priority)
    if is_awg:
        for k in ("jc", "jmin", "jmax", "s1", "s2", "h1", "h2", "h3", "h4"):
            user_val = getattr(server_data, f"awg_{k}", None)
            if user_val:
                awg_params[f"awg_{k}"] = user_val

    # For local servers without keys: generate new keypair
    if not public_key or not private_key:
        if is_awg:
            from ...core.amneziawg import AmneziaWGManager
            wg = AmneziaWGManager(interface=server_data.interface)
        else:
            from ...core.wireguard import WireGuardManager
            wg = WireGuardManager(interface=server_data.interface)
        private_key, public_key = wg.generate_keypair()
        wg.close()

    # split_tunnel_support is not applicable to AWG: AmneziaVPN handles it client-side
    # when AllowedIPs = 0.0.0.0/0 (full tunnel). Setting it for AWG is silently ignored.
    effective_split_tunnel = False if is_awg else server_data.split_tunnel_support

    server = core.servers.create_server(
        name=server_data.name,
        endpoint=server_data.endpoint,
        public_key=public_key,
        private_key=private_key,
        interface=server_data.interface,
        listen_port=listen_port,
        address_pool_ipv4=address_pool_ipv4,
        address_pool_ipv6=server_data.address_pool_ipv6,
        dns=server_data.dns,
        max_clients=server_data.max_clients,
        description=server_data.description,
        location=server_data.location,
        ssh_host=server_data.ssh_host,
        ssh_port=server_data.ssh_port,
        ssh_user=server_data.ssh_user,
        ssh_password=server_data.ssh_password,
        ssh_private_key=server_data.ssh_private_key,
        server_type=server_data.server_type,
        awg_mtu=server_data.awg_mtu,
        supports_peer_visibility=server_data.supports_peer_visibility,
        split_tunnel_support=effective_split_tunnel,
        **awg_params,
    )

    if not server:
        raise HTTPException(status_code=500, detail="Failed to create server")

    # AUTO-INSTALL AGENT for remote servers
    if server.ssh_host:
        logger.info(f"Auto-installing agent on {server.name}...")

        # Determine agent.py path dynamically
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        agent_code_path = os.path.join(base_dir, "agent.py")

        try:
            agent_installed, install_error = await asyncio.to_thread(
                core.servers.install_agent,
                server_id=server.id,
                agent_code_path=agent_code_path,
                port=8001,
            )

            if agent_installed:
                logger.info(f"Agent installed and activated on {server.name}")
            else:
                if server_data.provision:
                    # Provision failed — roll back server creation and surface the real error
                    await asyncio.to_thread(core.servers.delete_server, server.id, True)
                    raise HTTPException(
                        status_code=400,
                        detail=install_error or "Failed to provision server"
                    )
                logger.warning(f"Agent installation failed, staying in SSH mode: {install_error}")

        except HTTPException:
            raise
        except Exception as e:
            logger.error(f"Agent installation error: {e}")
            if server_data.provision:
                await asyncio.to_thread(core.servers.delete_server, server.id, True)
                raise HTTPException(status_code=400, detail=str(e))

    # Refresh server to get updated agent_mode
    db.refresh(server)

    # For local servers, re-sync status after creation so API responses do not
    # return a stale OFFLINE value when wg0 is already up.
    if not server.ssh_host:
        core.servers.check_server_status(server.id)
        db.refresh(server)

    return ServerResponse.from_server(server, db=db)


# ============================================================================
# PROXY SERVER CREATION HELPER
# ============================================================================

async def _create_proxy_server(server_data: "ServerCreate", db: Session, core: "ManagementCore"):
    """
    Create a Hysteria2 or TUIC proxy server.

    Flow:
    1. If ssh_host provided + provision=False → try to discover existing installation
    2. If not found (or no ssh_host) → write DB record only (provision must be called separately
       or set provision=True to auto-bootstrap on creation)
    3. If provision=True → bootstrap on remote server

    server_data.task_id: if provided, bootstrap log lines are emitted to the
    bootstrap_logger registry so the frontend can poll for live progress.
    """
    from ...modules.bootstrap_logger import create_task, get_task, attach_task_server
    from ...core.hysteria2 import Hysteria2Manager, DEFAULT_CONFIG_PATH as HY2_CFG, DEFAULT_SERVICE_NAME as HY2_SVC, DEFAULT_PORT as HY2_PORT, DEFAULT_CERT_PATH as HY2_CERT, DEFAULT_KEY_PATH as HY2_KEY
    from ...core.tuic import TUICManager, DEFAULT_CONFIG_PATH as TUIC_CFG, DEFAULT_SERVICE_NAME as TUIC_SVC, DEFAULT_PORT as TUIC_PORT, DEFAULT_CERT_PATH as TUIC_CERT, DEFAULT_KEY_PATH as TUIC_KEY

    is_hy2  = server_data.server_type == "hysteria2"
    is_tuic = server_data.server_type == "tuic"

    # Resolve defaults per protocol
    default_cfg  = HY2_CFG  if is_hy2 else TUIC_CFG
    default_svc  = HY2_SVC  if is_hy2 else TUIC_SVC
    default_port = HY2_PORT if is_hy2 else TUIC_PORT
    default_cert = HY2_CERT if is_hy2 else TUIC_CERT
    default_key  = HY2_KEY  if is_hy2 else TUIC_KEY

    listen_port = server_data.listen_port if server_data.listen_port != 51820 else default_port

    # Compute interface early — per-interface paths prevent shared-service conflicts
    prefix = f"proxy-{server_data.server_type[:3]}"
    existing_ifaces = {s.interface for s in db.query(Server).filter(Server.interface.like(f"{prefix}%")).all()}
    idx = 0
    while f"{prefix}{idx}" in existing_ifaces:
        idx += 1
    interface = f"{prefix}{idx}"

    # Derive per-interface isolated paths (each proxy gets its own service + config)
    if is_hy2:
        svc_name    = f"hysteria-{interface}"
        config_path = f"/etc/hysteria/config-{interface}.yaml"
        cert_path   = server_data.proxy_cert_path or f"/etc/hysteria/{interface}.crt"
        key_path    = server_data.proxy_key_path  or f"/etc/hysteria/{interface}.key"
    else:
        svc_name    = f"tuic-{interface}"
        config_path = f"/etc/tuic/config-{interface}.json"
        cert_path   = server_data.proxy_cert_path or f"/etc/tuic/{interface}.crt"
        key_path    = server_data.proxy_key_path  or f"/etc/tuic/{interface}.key"

    # Build manager kwargs
    mgr_kwargs = dict(
        config_path=config_path,
        service_name=svc_name,
        listen_port=listen_port,
        domain=server_data.proxy_domain,
        tls_mode=server_data.proxy_tls_mode or "self_signed",
        ssh_host=server_data.ssh_host,
        ssh_port=server_data.ssh_port,
        ssh_user=server_data.ssh_user,
        ssh_password=server_data.ssh_password,
        ssh_private_key=server_data.ssh_private_key,
        cert_path=cert_path,
        key_path=key_path,
    )
    proxy_auth_password = None
    if is_hy2:
        mgr_kwargs["obfs_password"] = server_data.proxy_obfs_password

    # Set up bootstrap progress logging
    task = None
    log_cb = None
    if server_data.task_id:
        task = create_task(server_data.task_id)
        log_cb = task.log

    def _log(msg: str):
        logger.info(msg)
        if log_cb:
            log_cb(msg)

    # If the user explicitly provided a domain or chose ACME/manual TLS, they want a
    # fresh configured installation — skip discover and go straight to bootstrap.
    user_wants_fresh = bool(
        server_data.proxy_domain
        or server_data.proxy_tls_mode in ("acme", "manual")
    )
    if user_wants_fresh and not server_data.provision:
        server_data.provision = True
        _log(f"ℹ Domain/TLS mode specified — installing fresh (skipping discover)")

    # Discover existing installation (local or remote) unless caller forces provision.
    # ProxyBaseManager._run() works locally when ssh_host=None, so discover() runs
    # for both local and remote servers.
    discovered = {}
    if not server_data.provision:
        try:
            host_label = server_data.ssh_host or "localhost"
            _log(f"🔍 Checking {host_label} for existing {server_data.server_type} installation...")
            if is_hy2:
                mgr = Hysteria2Manager(**mgr_kwargs)
            else:
                mgr = TUICManager(**{k: v for k, v in mgr_kwargs.items() if k != "obfs_password"})

            result = await asyncio.to_thread(mgr.discover)
            mgr.close()

            if result.get("found"):
                discovered = result
                config_path = result.get("config_path", config_path)
                listen_port = result.get("listen_port", listen_port)
                cert_path   = result.get("cert_path", cert_path)
                key_path    = result.get("key_path", key_path)
                svc_name = result.get("service_name", svc_name)
                mgr_kwargs["service_name"] = svc_name
                server_data.proxy_tls_mode = result.get("tls_mode", server_data.proxy_tls_mode or "self_signed")
                server_data.proxy_domain = result.get("domain", server_data.proxy_domain)
                if is_hy2:
                    server_data.proxy_obfs_password = result.get("obfs_password", server_data.proxy_obfs_password)
                    proxy_auth_password = result.get("auth_password")
                    if proxy_auth_password:
                        mgr_kwargs["auth_password"] = proxy_auth_password
                _log(f"✓ Found existing {server_data.server_type} installation at {config_path}")
            else:
                _log(
                    f"No existing {server_data.server_type} found (reason: {result.get('reason', 'unknown')}) "
                    "— will install fresh"
                )
                server_data.provision = True
        except Exception as e:
            if 'mgr' in dir():
                try:
                    mgr.close()
                except Exception:
                    pass
            if server_data.ssh_host:
                # SSH connection failure is a hard error for remote servers
                if task:
                    task.finish(error=f"SSH connection failed: {e}")
                raise HTTPException(status_code=400, detail=f"SSH connection failed: {e}")
            else:
                # For local servers, discovery failure is non-fatal — just provision
                logger.warning(f"Local discover failed ({e}), switching to provision mode")
                server_data.provision = True

    if is_hy2 and not proxy_auth_password:
        # Fresh bootstrap needs a stable server-level password that is also
        # persisted in the DB for later URI/config generation.
        import secrets as _secrets, string as _string
        _alphabet = _string.ascii_letters + _string.digits
        proxy_auth_password = "".join(_secrets.choice(_alphabet) for _ in range(32))
        mgr_kwargs["auth_password"] = proxy_auth_password

    # Create DB record (endpoint: host:port if port given, else just host)
    endpoint_host = server_data.endpoint.split(":")[0] if ":" in server_data.endpoint else server_data.endpoint
    endpoint = f"{endpoint_host}:{listen_port}"

    # placeholder keys not needed for proxy
    import secrets as _sec
    placeholder_key = _sec.token_hex(22)  # 44 hex chars, unique

    server = core.servers.create_server(
        name=server_data.name,
        endpoint=endpoint,
        public_key=placeholder_key,
        private_key=placeholder_key,
        interface=interface,
        listen_port=listen_port,
        address_pool_ipv4=server_data.address_pool_ipv4,
        address_pool_ipv6=None,
        dns=server_data.dns,
        max_clients=server_data.max_clients,
        description=server_data.description,
        location=server_data.location,
        ssh_host=server_data.ssh_host,
        ssh_port=server_data.ssh_port,
        ssh_user=server_data.ssh_user,
        ssh_password=server_data.ssh_password,
        ssh_private_key=server_data.ssh_private_key,
        server_type=server_data.server_type,
        server_category="proxy",
        proxy_domain=server_data.proxy_domain,
        proxy_tls_mode=server_data.proxy_tls_mode or "self_signed",
        proxy_cert_path=cert_path,
        proxy_key_path=key_path,
        proxy_config_path=config_path,
        proxy_service_name=svc_name,
        proxy_obfs_password=server_data.proxy_obfs_password if is_hy2 else None,
        proxy_auth_password=proxy_auth_password if is_hy2 else None,
        # VPN fields not applicable to proxy
        supports_peer_visibility=False,
        split_tunnel_support=False,
    )

    if not server:
        raise HTTPException(status_code=500, detail="Failed to create server record")
    if task:
        attach_task_server(server_data.task_id, server.id)

    # Bootstrap if requested (local servers have no ssh_host but still need provisioning)
    if server_data.provision:
        try:
            mgr_kwargs_final = dict(mgr_kwargs)
            mgr_kwargs_final.update({
                "config_path": config_path,
                "listen_port": listen_port,
                "cert_path": cert_path,
                "key_path": key_path,
            })
            if is_hy2:
                mgr = Hysteria2Manager(**mgr_kwargs_final)
            else:
                tuic_kwargs = {k: v for k, v in mgr_kwargs_final.items() if k != "obfs_password"}
                mgr = TUICManager(**tuic_kwargs)

            result = await asyncio.to_thread(mgr.bootstrap, [], log_cb)
            mgr.close()

            if not result.get("success"):
                await asyncio.to_thread(core.servers.delete_server, server.id, True)
                err_msg = result.get("message", "Bootstrap failed")
                if task:
                    task.finish(error=err_msg)
                raise HTTPException(status_code=400, detail=err_msg)

            logger.info(f"{server_data.server_type} bootstrapped on {server_data.ssh_host or 'localhost'}")
            # Update status to ONLINE after successful bootstrap
            await asyncio.to_thread(core.servers.check_server_status, server.id)
            if task:
                task.finish()
        except HTTPException:
            raise
        except Exception as e:
            await asyncio.to_thread(core.servers.delete_server, server.id, True)
            if task:
                task.finish(error=str(e))
            raise HTTPException(status_code=400, detail=str(e))
    else:
        # No bootstrap — but if discover found an existing installation, sync
        # the lifecycle status so the server doesn't stay stuck at OFFLINE.
        if discovered.get("found"):
            await asyncio.to_thread(core.servers.check_server_status, server.id)
        if task:
            task.finish()

    db.refresh(server)
    return ServerResponse.from_server(server, db=db)


@router.get("/bootstrap/{task_id}")
async def get_bootstrap_logs(task_id: str, since: int = Query(0, ge=0)):
    """
    Poll bootstrap progress logs for a proxy server installation.

    Returns new log lines since index `since` so the frontend can
    call this repeatedly without receiving duplicate lines.

    Response: {task_id, logs: [str], complete: bool, error: str|null, next_index: int}
    """
    from ...modules.bootstrap_logger import get_task
    task = get_task(task_id)
    if task is None:
        return JSONResponse({"task_id": task_id, "logs": [], "complete": True,
                             "error": "Task not found (may have expired)", "next_index": since})
    new_logs = task.get_logs_since(since)
    return JSONResponse({
        "task_id": task_id,
        "logs": new_logs,
        "complete": task.complete,
        "error": task.error,
        "next_index": since + len(new_logs),
    })


@router.post("/{server_id}/install-proxy")
async def install_proxy_on_server(
    server_id: int,
    req: ProxyInstallRequest,
    db: Session = Depends(get_db)
):
    """
    Install a proxy protocol (Hysteria2 or TUIC) on an existing server.

    The existing server must have SSH credentials stored. A new proxy Server
    record is created and bootstrap runs over SSH (same flow as creating a
    proxy server with provision=True).

    Use-case: you added a WireGuard server (or bare agent server) and now
    want to also install Hysteria2/TUIC on the same machine.

    Returns the newly created proxy ServerResponse.
    """
    from ...modules.bootstrap_logger import create_task, attach_task_server

    core = ManagementCore(db)
    src = core.get_server(server_id)
    if not src:
        raise HTTPException(status_code=404, detail="Source server not found")
    if not src.ssh_host:
        raise HTTPException(status_code=400, detail="Source server has no SSH credentials")

    from ...core.hysteria2 import (
        Hysteria2Manager,
        DEFAULT_CONFIG_PATH as HY2_CFG,
        DEFAULT_SERVICE_NAME as HY2_SVC,
        DEFAULT_PORT as HY2_PORT,
        DEFAULT_CERT_PATH as HY2_CERT,
        DEFAULT_KEY_PATH as HY2_KEY,
    )
    from ...core.tuic import (
        TUICManager,
        DEFAULT_CONFIG_PATH as TUIC_CFG,
        DEFAULT_SERVICE_NAME as TUIC_SVC,
        DEFAULT_PORT as TUIC_PORT,
        DEFAULT_CERT_PATH as TUIC_CERT,
        DEFAULT_KEY_PATH as TUIC_KEY,
    )

    is_hy2 = req.protocol == "hysteria2"
    default_port = req.port or (HY2_PORT if is_hy2 else TUIC_PORT)
    config_path = HY2_CFG if is_hy2 else TUIC_CFG
    cert_path = req.cert_path or (HY2_CERT if is_hy2 else TUIC_CERT)
    key_path = req.key_path or (HY2_KEY if is_hy2 else TUIC_KEY)
    svc_name = HY2_SVC if is_hy2 else TUIC_SVC

    # Inherit SSH from source server
    mgr_kwargs = dict(
        config_path=config_path,
        service_name=svc_name,
        listen_port=default_port,
        domain=req.domain,
        tls_mode=req.tls_mode,
        ssh_host=src.ssh_host,
        ssh_port=src.ssh_port or 22,
        ssh_user=src.ssh_user or "root",
        ssh_password=src.ssh_password,
        ssh_private_key=src.ssh_private_key,
        cert_path=cert_path,
        key_path=key_path,
    )

    # Generate stable auth password for Hysteria2
    proxy_auth_password = None
    if is_hy2:
        import secrets as _sec, string as _str
        proxy_auth_password = "".join(_sec.choice(_str.ascii_letters + _str.digits) for _ in range(32))
        mgr_kwargs["auth_password"] = proxy_auth_password
        mgr_kwargs["obfs_password"] = req.obfs_password

    # Set up progress logging
    task = None
    log_cb = None
    if req.task_id:
        task = create_task(req.task_id)
        log_cb = task.log

    def _log(msg: str):
        logger.info(msg)
        if log_cb:
            log_cb(msg)

    # Create proxy DB record
    import secrets as _sec2
    placeholder_key = _sec2.token_hex(22)
    endpoint_host = src.ssh_host
    endpoint = f"{endpoint_host}:{default_port}"
    interface = f"proxy-{req.protocol[:3]}0"
    name = req.name or f"{src.name} — {req.protocol.upper()}"

    server = core.servers.create_server(
        name=name,
        endpoint=endpoint,
        public_key=placeholder_key,
        private_key=placeholder_key,
        interface=interface,
        listen_port=default_port,
        address_pool_ipv4="10.66.66.0/24",
        address_pool_ipv6=None,
        dns="1.1.1.1",
        max_clients=250,
        description=f"Proxy installed on {src.name}",
        location=src.location,
        ssh_host=src.ssh_host,
        ssh_port=src.ssh_port,
        ssh_user=src.ssh_user,
        ssh_password=src.ssh_password,
        ssh_private_key=src.ssh_private_key,
        server_type=req.protocol,
        server_category="proxy",
        proxy_domain=req.domain,
        proxy_tls_mode=req.tls_mode,
        proxy_cert_path=cert_path,
        proxy_key_path=key_path,
        proxy_config_path=config_path,
        proxy_service_name=svc_name,
        proxy_obfs_password=req.obfs_password if is_hy2 else None,
        proxy_auth_password=proxy_auth_password if is_hy2 else None,
        supports_peer_visibility=False,
        split_tunnel_support=False,
    )
    if not server:
        if task:
            task.finish(error="Failed to create server record")
        raise HTTPException(status_code=500, detail="Failed to create server record")
    if task:
        attach_task_server(req.task_id, server.id)

    # Bootstrap
    try:
        _log(f"🚀 Installing {req.protocol.upper()} on {src.ssh_host}...")
        if is_hy2:
            mgr = Hysteria2Manager(**mgr_kwargs)
        else:
            tuic_kwargs = {k: v for k, v in mgr_kwargs.items() if k not in ("obfs_password", "auth_password")}
            mgr = TUICManager(**tuic_kwargs)

        result = await asyncio.to_thread(mgr.bootstrap, [], log_cb)
        mgr.close()

        if not result.get("success"):
            await asyncio.to_thread(core.servers.delete_server, server.id, True)
            err = result.get("message", "Bootstrap failed")
            if task:
                task.finish(error=err)
            raise HTTPException(status_code=400, detail=err)

        _log(f"✅ {req.protocol.upper()} installed successfully")
        if task:
            task.finish()
    except HTTPException:
        raise
    except Exception as e:
        await asyncio.to_thread(core.servers.delete_server, server.id, True)
        if task:
            task.finish(error=str(e))
        raise HTTPException(status_code=400, detail=str(e))

    db.refresh(server)
    return ServerResponse.from_server(server, db=db)


@router.get("/{server_id}", response_model=ServerResponse)
async def get_server(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Get server details
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    return ServerResponse.from_server(server, db=db)


@router.put("/{server_id}", response_model=ServerResponse)
async def update_server(
    server_id: int,
    server_data: ServerUpdate,
    db: Session = Depends(get_db)
):
    """
    Update server properties
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    update_data = server_data.model_dump(exclude_unset=True)

    # split_tunnel_support has no effect on AWG servers — silently drop it
    if update_data and getattr(server, 'server_type', 'wireguard') == 'amneziawg':
        update_data.pop('split_tunnel_support', None)

    if update_data:
        server = core.servers.update_server(server_id, **update_data)
        if not server:
            raise HTTPException(status_code=500, detail="Failed to update server")

    return ServerResponse.from_server(server, db=db)


@router.get("/{server_id}/delete-preview")
async def delete_server_preview(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Preview what will be affected by deleting a server.
    Use this before actually calling DELETE to show the user consequences.
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    from ...database.models import Client
    clients = db.query(Client).filter(Client.server_id == server_id).all()
    enabled_clients = [c for c in clients if c.enabled]

    return {
        "server_name": server.name,
        "server_id": server_id,
        "total_clients": len(clients),
        "enabled_clients": len(enabled_clients),
        "client_names": [c.name for c in clients],
        "warning": f"This will permanently delete server '{server.name}' and all {len(clients)} associated clients.",
        "requires_force": len(clients) > 0,
    }


@router.delete("/{server_id}")
async def delete_server(
    server_id: int,
    force: bool = Query(False, description="Delete even if has clients"),
    db: Session = Depends(get_db)
):
    """
    Delete a WireGuard server
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    if not core.servers.delete_server(server_id, force=force):
        raise HTTPException(
            status_code=400,
            detail="Failed to delete server. It may have clients - use force=true to delete anyway"
        )

    return {"message": f"Server '{server.name}' deleted successfully"}


@router.get("/{server_id}/stats", response_model=ServerStatsResponse)
async def get_server_stats(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Get server statistics including traffic and client counts
    """
    core = ManagementCore(db)
    stats = core.get_server_stats(server_id)

    if not stats:
        raise HTTPException(status_code=404, detail="Server not found")

    return stats


@router.get("/{server_id}/bandwidth")
async def get_server_bandwidth(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Get real-time bandwidth rates for a server.
    Call every 5 seconds for live monitoring.
    First call returns zero rates (baseline snapshot).
    """
    from ...core.bandwidth_monitor import BandwidthMonitor

    monitor = BandwidthMonitor(db)
    result = monitor.get_server_bandwidth(server_id)

    if not result:
        raise HTTPException(status_code=404, detail="Server not found or offline")

    return result


@router.post("/{server_id}/start")
async def start_server(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Start a WireGuard server interface
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    if not core.start_server(server_id):
        raise HTTPException(status_code=500, detail="Failed to start server")

    return {
        "message": f"Server '{server.name}' started",
        "status": "online"
    }


@router.post("/{server_id}/stop")
async def stop_server(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Stop a WireGuard server interface
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    if not core.stop_server(server_id):
        raise HTTPException(status_code=500, detail="Failed to stop server")

    return {
        "message": f"Server '{server.name}' stopped",
        "status": "offline"
    }


@router.post("/{server_id}/restart")
async def restart_server(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Restart a WireGuard server interface
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    if not core.servers.restart_server(server_id):
        raise HTTPException(status_code=500, detail="Failed to restart server")

    return {
        "message": f"Server '{server.name}' restarted",
        "status": "online"
    }


@router.get("/{server_id}/clients")
async def get_server_clients(
    server_id: int,
    enabled_only: bool = Query(False),
    db: Session = Depends(get_db)
):
    """
    Get all clients on a specific server
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    clients = core.clients.get_all_clients(
        server_id=server_id,
        enabled_only=enabled_only
    )

    return {
        "server_id": server_id,
        "server_name": server.name,
        "client_count": len(clients),
        "clients": [
            {
                "id": c.id,
                "name": c.name,
                "ipv4": c.ipv4,
                "enabled": c.enabled,
                "status": c.status.value,
            }
            for c in clients
        ]
    }


@router.get("/{server_id}/config")
async def get_server_config(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Get WireGuard server configuration file content
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    config = core.servers.generate_server_config(server_id)

    if not config:
        raise HTTPException(status_code=500, detail="Failed to generate config")

    return {"config": config}


@router.post("/{server_id}/save-config")
async def save_server_config(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Save server configuration to file
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    if not core.servers.save_server_config(server_id):
        raise HTTPException(status_code=500, detail="Failed to save config")

    return {
        "message": f"Configuration saved to {server.config_path}",
        "path": server.config_path
    }


@router.get("/{server_id}/agent-status")
async def get_agent_installation_status(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Get agent installation/health status

    Returns:
        - mode: "ssh" or "agent"
        - agent_healthy: true/false (if agent mode)
        - status: "ssh_only", "agent_online", "agent_offline"
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    response = {
        "server_id": server.id,
        "mode": server.agent_mode or "ssh",
        "agent_url": server.agent_url,
        "agent_healthy": False,
        "status": "ssh_only"
    }

    # Check agent health if in agent mode
    if server.agent_mode == "agent" and server.agent_url and server.agent_api_key:
        from ...core.agent_client import AgentClient

        try:
            client = AgentClient(server.agent_url, server.agent_api_key, timeout=5)
            health = client.health_check()
            response["agent_healthy"] = health
            response["status"] = "agent_online" if health else "agent_offline"
            client.close()
        except Exception:
            response["agent_healthy"] = False
            response["status"] = "agent_offline"
    elif server.agent_mode == "ssh":
        response["status"] = "ssh_only"

    return response


@router.post("/{server_id}/install-agent", dependencies=[_multi_server_gate])
async def install_agent_on_server(
    server_id: int,
    request: AgentInstallRequest,
    db: Session = Depends(get_db)
):
    """
    Manually install agent on existing remote server

    This endpoint allows installing the agent on servers that were added
    before Agent Mode was implemented, or if initial installation failed.

    Returns:
        - success: bool
        - message: str
        - agent_mode: "agent" or "ssh"
        - agent_url: str or null
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)

    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    # Check if it's a remote server
    if not server.ssh_host:
        raise HTTPException(
            status_code=400,
            detail="Cannot install agent on local server. Agent is only for remote servers."
        )

    # If already in agent mode, only skip if agent is actually healthy
    if server.agent_mode == "agent" and server.agent_url and server.agent_api_key:
        from ...core.agent_client import AgentClient
        try:
            client = AgentClient(server.agent_url, server.agent_api_key, timeout=5)
            is_healthy = client.health_check()
            client.close()
        except Exception:
            is_healthy = False
        if is_healthy:
            return {
                "success": True,
                "message": "Agent already installed and healthy",
                "agent_mode": "agent",
                "agent_url": server.agent_url
            }
        logger.info(f"Agent on {server.name} is unhealthy — proceeding with reinstall")

    # Install agent
    import os
    base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    agent_code_path = os.path.join(base_dir, "agent.py")

    logger.info(f"Installing agent on server {server.name} (ID: {server.id})...")

    try:
        agent_installed, install_error = await asyncio.to_thread(
            core.servers.install_agent,
            server_id=server.id,
            agent_code_path=agent_code_path,
            port=request.port,
        )

        if agent_installed:
            # Refresh server data
            db.refresh(server)

            logger.info(f"✅ Agent installed successfully on {server.name}")
            return {
                "success": True,
                "message": "Agent installed and activated successfully",
                "agent_mode": server.agent_mode,
                "agent_url": server.agent_url
            }
        else:
            logger.warning(f"⚠️ Agent installation failed on {server.name}: {install_error}")
            return {
                "success": False,
                "message": install_error or "Agent installation failed. Server remains in SSH mode. Check logs for details.",
                "agent_mode": "ssh",
                "agent_url": None
            }

    except Exception as e:
        logger.error(f"Agent installation error on {server.name}: {e}")
        raise HTTPException(
            status_code=500,
            detail=f"Agent installation failed: {str(e)}"
        )


@router.post("/discover", dependencies=[_multi_server_gate])
async def discover_server(
    data: DiscoverRequest,
    db: Session = Depends(get_db)
):
    """
    Discover WireGuard/AmneziaWG configuration on a remote server via SSH.
    Automatically registers the server, imports all clients, and installs the agent.
    """
    from ...core.amneziawg import AmneziaWGManager

    core = ManagementCore(db)

    is_awg = data.interface.startswith("awg")
    config_dir = "/etc/amneziawg" if is_awg else "/etc/wireguard"

    # Create appropriate manager for WG or AWG
    wg_kwargs = dict(
        interface=data.interface,
        config_path=f"{config_dir}/{data.interface}.conf",
        ssh_host=data.ssh_host,
        ssh_port=data.ssh_port,
        ssh_user=data.ssh_user,
        ssh_password=data.ssh_password,
        ssh_private_key=data.ssh_private_key,
    )
    wg = AmneziaWGManager(**wg_kwargs) if is_awg else WireGuardManager(**wg_kwargs)

    try:
        result = await asyncio.to_thread(wg.discover_remote)
    except Exception as e:
        wg.close()
        raise HTTPException(status_code=400, detail=f"SSH connection failed: {str(e)}")

    if not result:
        wg.close()
        raise HTTPException(
            status_code=400,
            detail=(
                f"{'AmneziaWG' if is_awg else 'WireGuard'} interface '{data.interface}' not found on {data.ssh_host}. "
                "Check: 1) interface name is correct (wg0/wg1/awg0), "
                "2) WireGuard is installed (wireguard-tools), "
                "3) config file exists at /etc/wireguard/{interface}.conf"
            )
        )

    wg.close()

    # Generate server name
    server_name = data.server_name or f"Server {data.ssh_host}"

    # Check for duplicate
    if core.servers.get_server_by_name(server_name):
        raise HTTPException(
            status_code=400,
            detail=f"Server '{server_name}' already exists"
        )

    # Create endpoint
    endpoint = f"{data.ssh_host}:{result['listen_port']}"

    # Register server + import clients in a SINGLE transaction
    try:
        # Build AWG-specific fields from discovered params (if AWG)
        awg_fields = {}
        if is_awg and result.get("awg_params"):
            p = result["awg_params"]
            awg_fields = {
                "awg_jc":   p.get("jc"),
                "awg_jmin": p.get("jmin"),
                "awg_jmax": p.get("jmax"),
                "awg_s1":   p.get("s1"),
                "awg_s2":   p.get("s2"),
                "awg_h1":   p.get("h1"),
                "awg_h2":   p.get("h2"),
                "awg_h3":   p.get("h3"),
                "awg_h4":   p.get("h4"),
            }

        server = Server(
            name=server_name,
            interface=data.interface,
            endpoint=endpoint,
            listen_port=result["listen_port"],
            public_key=result["public_key"],
            private_key=result["private_key"],
            address_pool_ipv4=result.get("address_pool_ipv4") or "10.66.66.0/24",
            address_pool_ipv6=result.get("address_pool_ipv6"),
            dns="1.1.1.1,1.0.0.1",
            config_path=f"{config_dir}/{data.interface}.conf",
            max_clients=250,
            status=ServerStatus.ONLINE,
            lifecycle_status=ServerLifecycleStatus.ONLINE.value,
            is_active=True,
            ssh_host=data.ssh_host,
            ssh_port=data.ssh_port,
            ssh_user=data.ssh_user,
            ssh_password=data.ssh_password,
            ssh_private_key=data.ssh_private_key,
            server_type="amneziawg" if is_awg else "wireguard",
            **awg_fields,
        )
        db.add(server)
        db.flush()  # Get server.id without committing

        # Import clients
        imported_clients = []
        for client_data in result.get("clients", []):
            # Calculate IP index from allowed_ips
            ip_index = 2
            if client_data.get("allowed_ips"):
                ip = client_data["allowed_ips"][0].split("/")[0]
                parts = ip.split(".")
                if len(parts) == 4:
                    ip_index = int(parts[3])

            # Extract IPv4 and IPv6
            ipv4 = None
            ipv6 = None
            for aip in client_data.get("allowed_ips", []):
                addr = aip.split("/")[0]
                if ":" in addr:
                    ipv6 = addr
                else:
                    ipv4 = addr

            client = Client(
                name=client_data.get("name", f"peer_{ip_index}"),
                server_id=server.id,
                public_key=client_data["public_key"],
                private_key=client_data.get("private_key"),
                preshared_key=client_data.get("preshared_key"),
                ip_index=ip_index,
                ipv4=ipv4,
                ipv6=ipv6,
                status=ClientStatus.ACTIVE,
                enabled=True,
            )
            db.add(client)
            imported_clients.append(client_data.get("name", f"peer_{ip_index}"))

        # Single commit: server + all clients atomically
        db.commit()
        db.refresh(server)

    except Exception as e:
        db.rollback()
        logger.error(f"Failed to discover/import server: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to import server: {str(e)}")

    # Auto-install agent (best-effort, non-fatal)
    agent_status = "not_attempted"
    try:
        import os
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
        agent_code_path = os.path.join(base_dir, "agent.py")
        agent_installed, _ = await asyncio.to_thread(
            core.servers.install_agent,
            server_id=server.id,
            agent_code_path=agent_code_path,
            port=8001,
        )
        if agent_installed:
            db.refresh(server)
            agent_status = "installed"
            logger.info(f"Agent auto-installed after discovery on {server.name}")
        else:
            agent_status = "failed"
    except Exception as e:
        logger.warning(f"Agent auto-install after discovery failed (non-fatal): {e}")
        agent_status = "failed"

    return {
        "message": f"Server '{server_name}' discovered and registered",
        "server": ServerResponse.from_server(server, db=db),
        "clients_imported": len(imported_clients),
        "client_names": imported_clients,
        "agent_status": agent_status,
    }


# ============================================================================
# BACKUP & RESTORE
# ============================================================================

@router.get("/{server_id}/backup")
async def backup_server(
    server_id: int,
    db: Session = Depends(get_db)
):
    """
    Export all clients of a server as a JSON backup.
    Includes WG keys, IPs, settings, traffic counters.
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)
    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    clients = db.query(Client).filter(Client.server_id == server_id).all()

    backup = {
        "version": "1.0",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "server": {
            "name": server.name,
            "endpoint": server.endpoint,
            "interface": server.interface,
            "listen_port": server.listen_port,
            "public_key": server.public_key,
            "address_pool_ipv4": server.address_pool_ipv4,
            "dns": server.dns,
        },
        "clients": []
    }

    for c in clients:
        backup["clients"].append({
            "name": c.name,
            "public_key": c.public_key,
            "private_key": c.private_key,
            "preshared_key": c.preshared_key,
            "ip_index": c.ip_index,
            "ipv4": c.ipv4,
            "ipv6": c.ipv6,
            "enabled": c.enabled,
            "status": c.status.value if hasattr(c.status, 'value') else str(c.status),
            "bandwidth_limit": c.bandwidth_limit,
            "traffic_limit_mb": c.traffic_limit_mb,
            "traffic_used_rx": c.traffic_used_rx,
            "traffic_used_tx": c.traffic_used_tx,
            "expiry_date": c.expiry_date.isoformat() if c.expiry_date else None,
        })

    logger.info(f"Backup created for server '{server.name}': {len(clients)} clients")
    return JSONResponse(
        content=backup,
        headers={
            "Content-Disposition": f'attachment; filename="backup_{_safe_filename(server.name)}_{datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")}.json"'
        }
    )


@router.post("/{server_id}/restore")
async def restore_server(
    server_id: int,
    file: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    """
    Restore clients from a JSON backup file.
    Skips clients that already exist (by public_key).
    """
    core = ManagementCore(db)
    server = core.get_server(server_id)
    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    try:
        content = await file.read()
        backup = json.loads(content)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Invalid backup file: {str(e)}")

    if "clients" not in backup:
        raise HTTPException(status_code=400, detail="Invalid backup format: missing 'clients' key")

    restored = 0
    skipped = 0
    errors = []

    for cd in backup["clients"]:
        # Check if client with this public_key already exists
        existing = db.query(Client).filter(Client.public_key == cd["public_key"]).first()
        if existing:
            skipped += 1
            continue

        # Check IP conflict
        if cd.get("ipv4"):
            ip_conflict = db.query(Client).filter(
                Client.server_id == server_id,
                Client.ipv4 == cd["ipv4"]
            ).first()
            if ip_conflict:
                errors.append(f"{cd['name']}: IP {cd['ipv4']} already in use")
                skipped += 1
                continue

        from ...database.models import ClientStatus as CS

        status_map = {"active": CS.ACTIVE, "disabled": CS.DISABLED, "expired": CS.EXPIRED}
        client_status = status_map.get(cd.get("status", "active"), CS.ACTIVE)

        expiry = None
        if cd.get("expiry_date"):
            try:
                expiry = datetime.fromisoformat(cd["expiry_date"])
                if expiry.tzinfo is None:
                    expiry = expiry.replace(tzinfo=timezone.utc)
            except Exception:
                pass

        client = Client(
            name=cd["name"],
            server_id=server_id,
            public_key=cd["public_key"],
            private_key=cd.get("private_key"),
            preshared_key=cd.get("preshared_key"),
            ip_index=cd.get("ip_index", 0),
            ipv4=cd.get("ipv4", ""),
            ipv6=cd.get("ipv6"),
            enabled=cd.get("enabled", True),
            status=client_status,
            bandwidth_limit=cd.get("bandwidth_limit"),
            traffic_limit_mb=cd.get("traffic_limit_mb"),
            traffic_used_rx=cd.get("traffic_used_rx", 0),
            traffic_used_tx=cd.get("traffic_used_tx", 0),
            expiry_date=expiry,
        )
        db.add(client)
        restored += 1

    try:
        db.commit()
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Database error: {str(e)}")

    logger.info(f"Restore to server '{server.name}': {restored} restored, {skipped} skipped")
    return {
        "message": f"Restore complete: {restored} clients restored, {skipped} skipped",
        "restored": restored,
        "skipped": skipped,
        "errors": errors,
    }


@router.post("/{server_id}/set-default")
async def set_default_server(
    server_id: int,
    db: Session = Depends(get_db),
):
    """Set a server as the default for auto-provisioned clients (subscriptions, client portal)"""
    core = ManagementCore(db)
    success = core.servers.set_default_server(server_id)
    if not success:
        raise HTTPException(status_code=404, detail="Server not found")
    return {"message": f"Server {server_id} set as default", "server_id": server_id}


@router.post("/{server_id}/reconcile")
async def reconcile_server(
    server_id: int,
    db: Session = Depends(get_db),
):
    """
    Manually trigger drift detection + reconciliation for a single server.
    Re-adds any peers missing from the live WireGuard interface (safe drift).
    Sets drift_detected=True for unsafe drifts (interface down, agent broken).
    """
    server = db.query(Server).filter(Server.id == server_id).first()
    if not server:
        raise HTTPException(status_code=404, detail="Server not found")

    from ...modules.state_reconciler import reconcile_server as _reconcile
    try:
        result = _reconcile(server, db)
        db.commit()
    except Exception as e:
        db.rollback()
        logger.error(f"Reconcile error for server {server_id}: {e}")
        raise HTTPException(status_code=500, detail=f"Reconciliation failed: {e}")

    return result
