"""Validation schemas and server response serialization for server routes."""

from datetime import datetime
import ipaddress
from typing import Dict, Optional

from pydantic import BaseModel, Field, field_validator

from ...database.models import Client

# security: shared constraints for operator-supplied fields that are later
# interpolated into root shell commands (iptables/PostUp, openssl, certbot).
# Rejecting bad values with 422 at the API boundary is defense-in-depth on top
# of the shlex.quote() applied at each shell sink.
_HOSTNAME_PATTERN = r"^[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*$"
_TLS_PATH_PATTERN = r"^/[A-Za-z0-9._/-]{1,200}$"


def _validate_ipv4_pool(v):
    """Reject any address_pool_ipv4 that isn't a parseable IPv4 network (→422)."""
    if v is None:
        return v
    try:
        ipaddress.ip_network(v, strict=False)
    except (ValueError, TypeError) as e:
        raise ValueError(f"Invalid IPv4 network for address_pool_ipv4: {v!r}") from e
    return v


# ============================================================================
# SCHEMAS
# ============================================================================

class ServerCreate(BaseModel):
    """Schema for creating a new server"""
    name: str = Field(..., min_length=1, max_length=100)
    endpoint: str = Field(..., description="Public endpoint (ip:port)")
    public_key: Optional[str] = Field(None, min_length=44, max_length=44)
    private_key: Optional[str] = Field(None, min_length=44, max_length=44)
    interface: str = Field("wg0", pattern=r"^(wg|awg)\d+$")
    listen_port: int = Field(51820, ge=1, le=65535)
    address_pool_ipv4: str = Field("10.66.0.0/19")
    address_pool_ipv6: Optional[str] = Field("fd42:42:42::/64")
    dns: str = Field("1.1.1.1,1.0.0.1")
    max_clients: int = Field(8000, ge=1)
    description: Optional[str] = None
    location: Optional[str] = None
    ssh_host: Optional[str] = Field(None, description="SSH host for remote management")
    ssh_port: int = Field(22, ge=1, le=65535)
    ssh_user: str = Field("root")
    ssh_password: Optional[str] = Field(None, description="SSH password")
    ssh_private_key: Optional[str] = Field(None, description="SSH private key content (PEM). Use instead of password.")
    # Protocol type: vpn or proxy
    server_type: str = Field(
        "wireguard",
        pattern=r"^(wireguard|amneziawg|hysteria2|tuic|vless-reality)$",
        description="Protocol: wireguard | amneziawg | hysteria2 | tuic | vless-reality",
    )
    # AmneziaWG obfuscation params (VPN only)
    awg_jc: Optional[int] = Field(None, ge=1, le=128)
    awg_jmin: Optional[int] = Field(None, ge=0, le=65535)
    awg_jmax: Optional[int] = Field(None, ge=0, le=65535)
    awg_s1: Optional[int] = Field(None, ge=0, le=65535)
    awg_s2: Optional[int] = Field(None, ge=0, le=65535)
    awg_h1: Optional[int] = Field(None, ge=1)
    awg_h2: Optional[int] = Field(None, ge=1)
    awg_h3: Optional[int] = Field(None, ge=1)
    awg_h4: Optional[int] = Field(None, ge=1)
    awg_mtu: Optional[int] = Field(None, ge=576, le=9000, description="MTU for AWG (default 1280 if not set)")
    supports_peer_visibility: bool = Field(True, description="Whether this server supports peer visibility")
    split_tunnel_support: bool = Field(False, description="Use VPN subnet AllowedIPs to enable AmneziaVPN split tunneling")
    ipv4_only: bool = Field(False, description="Strip IPv6 from generated client configs (DNS-leak hygiene)")
    customer_visible: bool = Field(True, description="Show this server in /client-portal/servers (set False for test boxes)")
    for_app_only: bool = Field(False, description="Only surface to the official mobile/desktop app — router/openVPN clients and web users never see it")
    force_visible: bool = Field(False, description="Bypass the auto-hide-after-N-minutes-unreachable filter for this server")
    provision: bool = Field(False, description="Provision a fresh server: install protocol, generate keys/certs, start service")
    task_id: Optional[str] = Field(None, description="Bootstrap task ID for progress tracking (generated by frontend)")
    # Proxy protocol fields (hysteria2 / tuic)
    # security: hostname-only / absolute-path-only so $(...)/;/backticks can't
    # reach the certbot/openssl shell commands built from these values.
    proxy_domain: Optional[str] = Field(
        None, max_length=253, pattern=_HOSTNAME_PATTERN,
        description="Domain name for TLS SNI (proxy only)",
    )
    proxy_tls_mode: str = Field("self_signed", description="TLS mode: self_signed | acme | manual (proxy only)")
    proxy_cert_path: Optional[str] = Field(
        None, pattern=_TLS_PATH_PATTERN,
        description="Path to TLS cert on server (proxy manual TLS)",
    )
    proxy_key_path: Optional[str] = Field(
        None, pattern=_TLS_PATH_PATTERN,
        description="Path to TLS key on server (proxy manual TLS)",
    )
    proxy_obfs_password: Optional[str] = Field(None, description="OBFS password (Hysteria2 only)")

    # ── Mikrotik RouterOS REST mode ────────────────────────────────────────
    # When `agent_mode='mikrotik'`, the server is managed via RouterOS REST.
    # We reuse `agent_url` to carry the full URL (e.g. "http://1.2.3.4")
    # and `agent_api_key` to carry "user:password" — no schema migration
    # needed. SSH fields are ignored in this mode.
    agent_mode: str = Field(
        "ssh",
        pattern=r"^(ssh|agent|mikrotik)$",
        description="Connection mode: ssh (default), agent (HTTP daemon), mikrotik (RouterOS REST API)",
    )
    mikrotik_url: Optional[str] = Field(
        None,
        description="RouterOS REST endpoint URL (e.g. http://1.2.3.4 or https://router.example.com:443). "
                    "Required when agent_mode=mikrotik.",
    )
    mikrotik_username: Optional[str] = Field(None, description="RouterOS API username")
    mikrotik_password: Optional[str] = Field(None, description="RouterOS API password")

    # security: the client subnet is later interpolated into root iptables/PostUp
    # rules — reject a non-IPv4-network value with 422 before it can be stored.
    @field_validator("address_pool_ipv4")
    @classmethod
    def _validate_pool(cls, v):
        return _validate_ipv4_pool(v)

    class Config:
        json_schema_extra = {
            "example": {
                "name": "Amsterdam Server",
                "endpoint": "1.2.3.4:51820",
                "public_key": "example_public_key_base64_44chars==",
                "private_key": "example_private_key_base64_44chars=",
                "interface": "wg1",
                "location": "Netherlands",
                "ssh_host": "1.2.3.4",
                "ssh_password": "secret"
            }
        }


class ServerUpdate(BaseModel):
    """Schema for updating a server"""
    name: Optional[str] = Field(None, min_length=1, max_length=100)
    display_name: Optional[str] = Field(None, max_length=100)
    endpoint: Optional[str] = None
    dns: Optional[str] = None
    max_clients: Optional[int] = Field(None, ge=1)
    max_bandwidth_mbps: Optional[int] = Field(None, ge=0)
    description: Optional[str] = None
    location: Optional[str] = None
    supports_peer_visibility: Optional[bool] = None
    split_tunnel_support: Optional[bool] = None
    ipv4_only: Optional[bool] = None
    # Toggle to hide / show this server in the client portal's location
    # picker. False = test / staging server, admin-only.
    customer_visible: Optional[bool] = None
    # Per-platform visibility (migration 046). False on one of these
    # hides the server only on the matching client app; the other
    # platform and the web portal continue to see it.
    customer_visible_mobile: Optional[bool] = None
    customer_visible_windows: Optional[bool] = None
    # App-only visibility + admin override for auto-hide. See model
    # docstring on Server.for_app_only / Server.force_visible.
    for_app_only: Optional[bool] = None
    force_visible: Optional[bool] = None
    # AmneziaWG obfuscation parameters. Editable post-creation so a server
    # migrated from another box can be made to match the old box's headers,
    # keeping existing client configs working without re-issuing them.
    # When any of these change the PUT handler redeploys the AWG config to
    # disk and restarts the interface so the kernel module picks them up.
    awg_jc: Optional[int] = Field(None, ge=1, le=128)
    awg_jmin: Optional[int] = Field(None, ge=0, le=65535)
    awg_jmax: Optional[int] = Field(None, ge=0, le=65535)
    awg_s1: Optional[int] = Field(None, ge=0, le=65535)
    awg_s2: Optional[int] = Field(None, ge=0, le=65535)
    awg_h1: Optional[int] = Field(None, ge=1)
    awg_h2: Optional[int] = Field(None, ge=1)
    awg_h3: Optional[int] = Field(None, ge=1)
    awg_h4: Optional[int] = Field(None, ge=1)
    awg_mtu: Optional[int] = Field(None, ge=576, le=9000)


class ProxyInstallRequest(BaseModel):
    """Schema for installing a proxy protocol on an existing SSH-accessible server."""
    protocol: str = Field("hysteria2", pattern=r"^(hysteria2|tuic|vless-reality)$")
    name: Optional[str] = None
    port: Optional[int] = Field(None, ge=1, le=65535)
    tls_mode: str = Field("self_signed", pattern=r"^(self_signed|acme|manual)$")
    # security: constrain fields that flow into certbot/openssl/test shell calls
    domain: Optional[str] = Field(None, max_length=253, pattern=_HOSTNAME_PATTERN)
    cert_path: Optional[str] = Field(None, pattern=_TLS_PATH_PATTERN)
    key_path: Optional[str] = Field(None, pattern=_TLS_PATH_PATTERN)
    obfs_password: Optional[str] = None  # Hysteria2 only
    task_id: Optional[str] = None


class AwgInstallRequest(BaseModel):
    """Schema for installing AmneziaWG on an existing SSH-accessible server."""
    name: Optional[str] = None
    # security: match the validated ServerCreate.interface pattern — the
    # interface name is interpolated into the root PostUp iptables rules.
    interface: Optional[str] = Field(None, pattern=r"^(wg|awg)\d+$")  # e.g. "awg1" — auto-picked if omitted
    listen_port: Optional[int] = Field(None, ge=1, le=65535)
    address_pool_ipv4: str = "10.66.0.0/19"
    address_pool_ipv6: Optional[str] = None
    dns: str = "1.1.1.1"
    task_id: Optional[str] = None

    # security: reject a non-IPv4-network pool before it reaches the AWG PostUp rule
    @field_validator("address_pool_ipv4")
    @classmethod
    def _validate_pool(cls, v):
        return _validate_ipv4_pool(v)


class ServerResponse(BaseModel):
    """Server response schema"""
    id: int
    name: str
    display_name: Optional[str] = None
    interface: str
    endpoint: str
    listen_port: int
    # Network identity is intentionally part of the list response: the active
    # admin UI renders it in each server card's Details disclosure.  Keeping
    # these fields only on the ORM model made the new UI show an em dash even
    # though the server was configured correctly.
    public_key: Optional[str] = None
    address_pool_ipv4: Optional[str] = None
    status: str
    lifecycle_status: str
    is_active: bool = True
    max_clients: int
    total_clients: int = 0
    description: Optional[str]
    location: Optional[str]
    ssh_host: Optional[str] = None
    ssh_port: int = 22
    ssh_user: str = "root"
    is_remote: bool = False
    agent_mode: str = "ssh"  # "ssh" or "agent"
    agent_url: Optional[str] = None
    # In-memory circuit-breaker state for this server's agent. Populated by
    # ServerResponse.from_server() from src.core.agent_client._breaker_state.
    # `null` when the server isn't in agent mode or has never failed.
    # When set, panel UI shows a red "Agent unreachable" badge + a banner
    # offering Switch-to-SSH / Retry-now so the user can clear the lag
    # without trawling menus. See src/core/agent_client.py:get_breaker_state.
    agent_breaker: Optional[Dict[str, object]] = None
    # AGENT_VERSION reported by the agent's last-successful /health, surfaced so
    # the operator can see which nodes are on the current agent build (e.g. after
    # a reinstall). `null` for SSH-mode servers or agents not yet health-probed.
    agent_version: Optional[str] = None
    max_bandwidth_mbps: Optional[int] = None
    is_default: bool = False
    server_type: str = "wireguard"
    server_category: str = "vpn"
    # VPN (WG/AWG) fields
    awg_jc: Optional[int] = None
    awg_jmin: Optional[int] = None
    awg_jmax: Optional[int] = None
    awg_s1: Optional[int] = None
    awg_s2: Optional[int] = None
    awg_h1: Optional[int] = None
    awg_h2: Optional[int] = None
    awg_h3: Optional[int] = None
    awg_h4: Optional[int] = None
    awg_mtu: Optional[int] = None
    supports_peer_visibility: bool = True
    split_tunnel_support: bool = False
    ipv4_only: bool = False
    customer_visible: bool = True
    customer_visible_mobile: bool = True
    customer_visible_windows: bool = True
    for_app_only: bool = False
    force_visible: bool = False
    last_good_health_at: Optional[datetime] = None
    # Proxy fields
    proxy_domain: Optional[str] = None
    proxy_tls_mode: Optional[str] = None
    proxy_cert_path: Optional[str] = None
    proxy_key_path: Optional[str] = None
    proxy_config_path: Optional[str] = None
    proxy_service_name: Optional[str] = None

    class Config:
        from_attributes = True

    @staticmethod
    def _breaker_for(server) -> Optional[Dict[str, object]]:
        """Return the live circuit-breaker view for this server, or None when
        not applicable (SSH-only, no agent_url, or fresh state with zero fails).
        We hide the all-clear case so the frontend can simply check
        `server.agent_breaker?.open` without filtering empty objects."""
        if (server.agent_mode or "ssh") != "agent" or not server.agent_url:
            return None
        try:
            from ...core.agent_client import get_breaker_state
            state = get_breaker_state(server.agent_url)
        except Exception:
            return None
        if not state.get("open") and not state.get("fails"):
            return None
        return state

    @staticmethod
    def _agent_version_for(server) -> Optional[str]:
        """AGENT_VERSION from the agent's last-successful /health (cached), or
        None when not an agent server / never successfully probed."""
        if (server.agent_mode or "ssh") != "agent" or not server.agent_url:
            return None
        try:
            from ...core.agent_health_cache import get_cached_health
            # Generous max-age: the version is informational and changes rarely,
            # so show the last-known build even if the latest probe lagged.
            cached = get_cached_health(server.agent_url, max_age_sec=3600)
            if cached:
                data, _age = cached
                if isinstance(data, dict):
                    v = data.get("version")
                    return str(v) if v else None
        except Exception:
            return None
        return None

    @classmethod
    def from_server(cls, server, db=None, total_clients=None):
        # `total_clients` may be pre-computed by the caller (avoids N+1 in
        # list endpoints — see list_servers below). When None, fall back to a
        # per-server COUNT — fine for single-server endpoints, expensive in
        # a loop. Always pass it from list contexts.
        if total_clients is None:
            total_clients = 0
            if db:
                total_clients = db.query(Client).filter(Client.server_id == server.id).count()

        server_type = getattr(server, 'server_type', 'wireguard') or 'wireguard'
        server_category = getattr(server, 'server_category', None)
        if not server_category:
            server_category = 'proxy' if server_type in ('hysteria2', 'tuic') else 'vpn'

        return cls(
            id=server.id,
            name=server.name,
            display_name=getattr(server, 'display_name', None),
            interface=server.interface,
            endpoint=server.endpoint,
            listen_port=server.listen_port,
            public_key=getattr(server, 'public_key', None),
            address_pool_ipv4=getattr(server, 'address_pool_ipv4', None),
            status=server.legacy_status.value if hasattr(server, 'legacy_status') else (server.status.value if hasattr(server.status, 'value') else str(server.status)),
            lifecycle_status=server.effective_lifecycle_status if hasattr(server, 'effective_lifecycle_status') else str(server.status),
            is_active=getattr(server, 'is_active', True),
            max_clients=server.max_clients,
            total_clients=total_clients,
            description=server.description,
            location=server.location,
            ssh_host=server.ssh_host,
            ssh_port=server.ssh_port or 22,
            ssh_user=server.ssh_user or "root",
            is_remote=server.ssh_host is not None,
            agent_mode=server.agent_mode or "ssh",
            agent_url=server.agent_url,
            agent_breaker=cls._breaker_for(server),
            agent_version=cls._agent_version_for(server),
            max_bandwidth_mbps=server.max_bandwidth_mbps,
            is_default=getattr(server, 'is_default', False) or False,
            server_type=server_type,
            server_category=server_category,
            awg_jc=getattr(server, 'awg_jc', None),
            awg_jmin=getattr(server, 'awg_jmin', None),
            awg_jmax=getattr(server, 'awg_jmax', None),
            awg_s1=getattr(server, 'awg_s1', None),
            awg_s2=getattr(server, 'awg_s2', None),
            awg_h1=getattr(server, 'awg_h1', None),
            awg_h2=getattr(server, 'awg_h2', None),
            awg_h3=getattr(server, 'awg_h3', None),
            awg_h4=getattr(server, 'awg_h4', None),
            awg_mtu=getattr(server, 'awg_mtu', None),
            supports_peer_visibility=getattr(server, 'supports_peer_visibility', True),
            split_tunnel_support=getattr(server, 'split_tunnel_support', False),
            ipv4_only=getattr(server, 'ipv4_only', False),
            customer_visible=getattr(server, 'customer_visible', True),
            customer_visible_mobile=getattr(server, 'customer_visible_mobile', True),
            customer_visible_windows=getattr(server, 'customer_visible_windows', True),
            for_app_only=getattr(server, 'for_app_only', False),
            force_visible=getattr(server, 'force_visible', False),
            last_good_health_at=getattr(server, 'last_good_health_at', None),
            proxy_domain=getattr(server, 'proxy_domain', None),
            proxy_tls_mode=getattr(server, 'proxy_tls_mode', None),
            proxy_cert_path=getattr(server, 'proxy_cert_path', None),
            proxy_key_path=getattr(server, 'proxy_key_path', None),
            proxy_config_path=getattr(server, 'proxy_config_path', None),
            proxy_service_name=getattr(server, 'proxy_service_name', None),
        )


class DiscoverRequest(BaseModel):
    """Schema for discovering a remote server"""
    ssh_host: str = Field(..., description="SSH host/IP")
    ssh_port: int = Field(22, ge=1, le=65535)
    ssh_user: str = Field("root")
    ssh_password: Optional[str] = Field(None, description="SSH password")
    ssh_private_key: Optional[str] = Field(None, description="SSH private key content (PEM). Use instead of password.")
    interface: str = Field("wg0", pattern=r"^(wg|awg)\d+$")
    server_name: Optional[str] = Field(None, description="Name for the server (auto-generated if empty)")


class ServerStatsResponse(BaseModel):
    """Server statistics response"""
    server_id: int
    name: str
    interface: str
    status: str
    endpoint: str
    total_clients: int
    active_clients: int
    max_clients: int
    capacity_percent: float
    total_rx: int
    total_tx: int
    total_traffic: int
    is_online: bool


class AgentInstallRequest(BaseModel):
    """Schema for agent installation"""
    port: int = Field(8001, ge=1, le=65535, description="Agent API port")
    # Stream install progress to this bootstrap-log task id (frontend polls
    # GET /servers/bootstrap/{task_id}); null = no streaming.
    task_id: Optional[str] = None
    # Reinstall even when the current agent is healthy — needed to push a new
    # agent build (e.g. upgrading 1.4.0 → 1.5.0) onto an already-working node.
    force: bool = False
